### ISSUE TITLE
How to know deterministically know when a consumer is ready?

### ISSUE THREAD

**Issue by apeloquin-agilysys** [confluentinc/confluent-kafka-javascript#118]
In KafkaJS we make use of the `consumer.group_join` event for our application to know a consumer is ready to receive messages.

```typescript
consumer.on(consumer.events.GROUP_JOIN, (event: ConsumerGroupJoinEvent) => {
  // inform app this consumer is ready
});
```

Per #38, the `on` methods don't appear to be on the immediate road map.
> About the on methods, we don't plan to implement them yet.

I'm wondering if you have an alternative approach we can use to ascertain consumer readiness?

Originally we were using this:
```typescript
consumer.assignment().length > 0
```
Unfortunately, it turns out that when you have a topic with more consumers than partitions, the consumers that don't get a partition also never satisfy this condition.

I see we get log entries:
```json
{
  "message": "Consumer connected",
  "extra": {
    "fac": "BINDING",
    "name": "undefined#consumer-1"
  }
}
```
...but even if we were to hijack these events with our own _Logger_, I see no way to tie the `name` back to the consumers created (in our case we may have dozens).

**Comment by apeloquin-agilysys** [comment]
Sorry, I just noticed this very much overlaps with #65.

**Comment by milindl** [comment]
Hello @apeloquin-agilysys , I think the right way here would be to look at the rebalance callback. It is triggered every time there's a rebalance, even if the said consumer has received no partitions as a result of the rebalance call. It could look something like this, you could wait on `firstRebalanceComplete`.

```js
  const { ErrorCodes } = require('@confluentinc/kafka-javascript').KafkaJS;
  // ...
  let firstRebalanceComplete = false;
  consumer = kafka.consumer({
    kafkaJS: {
      clientId: cName,
      // Other config properties
    },
    'rebalance_cb': (err, assignment) => {
      switch (err.code) {
        case ErrorCodes.ERR__ASSIGN_PARTITIONS:
          console.log(`Assigned partitions ${JSON.stringify(assignment)}`); // This could be [] too
          if (!firstRebalanceComplete) {
            firstRebalanceComplete = true;
            console.log("Completed first rebalance for consumer " + cName);
          }
          break;
        case ErrorCodes.ERR__REVOKE_PARTITIONS:
          // You don't need to take any action for any of the other cases. Including them just for illustrative reasons
          break;
        default:
          console.error(err);
      }
    },
  });
```

**Comment by apeloquin-agilysys** [comment]
Thanks.  I arrived at a similar (but less complete) conclusion based on the comment by _justjake_ on #65.

There are a lot of callbacks available in GlobalConfig, ConsumerGlobalConfig, ProducerGlobalConfig, etc.  However, the comments and typing `config.d.ts` don't provide much transparency in terms of usage for folks coming from a KafkaJS/Typescript transition (e.g. `any` and `Function` lead to internet searches hoping to find example code).  Any plans to improve this?  

```typescript
    /**
     * Error callback (set with rd_kafka_conf_set_error_cb())
     */
    "error_cb"?: any;

    /**
     * Throttle callback (set with rd_kafka_conf_set_throttle_cb())
     */
    "throttle_cb"?: any;

    /**
     * Statistics callback (set with rd_kafka_conf_set_stats_cb())
     */
    "stats_cb"?: any;

    /**
     * Log callback (set with rd_kafka_conf_set_log_cb())
     */
    "log_cb"?: any;

    /**
     * Background queue event callback (set with rd_kafka_conf_set_background_event_cb())
     */
    "background_event_cb"?: any;

    /**
     * Socket creation callback to provide race-free CLOEXEC
     */
    "socket_cb"?: any;

    /**
     * Socket connect callback
     */
    "connect_cb"?: any;

    /**
     * Socket close callback
     */
    "closesocket_cb"?: any;

    /**
     * File open callback to provide race-free CLOEXEC
     */
    "open_cb"?: any;

    /**
     * Address resolution callback (set with rd_kafka_conf_set_resolve_cb()).
     */
    "resolve_cb"?: any;
    
    /**
     * Delivery report callback (set with rd_kafka_conf_set_dr_cb())
     */
    "dr_cb"?: boolean | Function;

    /**
     * Delivery report callback (set with rd_kafka_conf_set_dr_msg_cb())
     */
    "dr_msg_cb"?: boolean;

    /**
     * Callback to verify the broker certificate chain.
     */
    "ssl.certificate.verify_cb"?: any;
    
    /**
     * SASL/OAUTHBEARER token refresh callback (set with rd_kafka_conf_set_oauthbearer_token_refresh_cb(), triggered by rd_kafka_poll(), et.al. This callback will be triggered when it is time to refresh the client's OAUTHBEARER token. Also see `rd_kafka_conf_enable_sasl_queue()`.
     */
    "oauthbearer_token_refresh_cb"?: any;
    
    /**
     * Message consume callback (set with rd_kafka_conf_set_consume_cb())
     */
    "consume_cb"?: any;

    /**
     * Called after consumer group has been rebalanced (set with rd_kafka_conf_set_rebalance_cb())
     */
    "rebalance_cb"?: boolean | Function;

    /**
     * Offset commit result propagation callback. (set with rd_kafka_conf_set_offset_commit_cb())
     */
    "offset_commit_cb"?: boolean | Function;
    
    /**
     * Custom partitioner callback (set with rd_kafka_topic_conf_set_partitioner_cb())
     */
    "partitioner_cb"?: any;
```

**Comment by milindl** [comment]
I agree - the config.d.ts is auto-generated, and while the non-callback properties are commented pretty accurately, the callback properties are lacking. I'll look at improving it, and removing those callbacks from the typing which aren't supported.

**Comment by milindl** [comment]
Closing this out with the resolution, I'll address a bunch of typing and documentation issues together in #139 .

**Comment by justjake** [comment]
What I do these days is resolve a Promise in the first rebalance_cb call. It’s similar to @milindl’s example but I’m calling `resolve()` where the example does `firstRebalanceComplete = true`
