### ISSUE TITLE
SchemaRegistry cacheLatestTtlSecs setting is ignored

### ISSUE THREAD

**Issue by apeloquin-agilysys** [confluentinc/confluent-kafka-javascript#143]
The `cacheLatestTtlSecs` config setting is used to set `maxAge` which is passed to _lru-cache_.  `maxAge` is no longer supported (replaced by `ttl`).  

```typescript
    const cacheOptions = {
      max: config.cacheCapacity !== undefined ? config.cacheCapacity : 1000,
      ...(config.cacheLatestTtlSecs !== undefined && { maxAge: config.cacheLatestTtlSecs * 1000 })
    };

    // ...
    
    this.schemaToIdCache = new LRUCache(cacheOptions);
```

This happens in at least two places: [here](https://github.com/confluentinc/confluent-kafka-javascript/blob/e1bd8e844e841fa08545589bee26e1f90a2f796e/schemaregistry/schemaregistry-client.ts#L199-L213) and [here](https://github.com/confluentinc/confluent-kafka-javascript/blob/master/schemaregistry/rules/encryption/dekregistry/dekregistry-client.ts#L67-L76)

**Comment by Claimundefine** [comment]
https://github.com/confluentinc/confluent-kafka-javascript/pull/160 Addressed in this PR.
