### ISSUE TITLE
Compression doesn't work on the producer level.

### ISSUE THREAD

**Issue by maksym-opanasenko-ft** [confluentinc/confluent-kafka-javascript#201]
Environment Information

- Reproduced on Mac (silicone)
- Node Version: v18.20.4
- NPM Version: 10.7.0
- Confluent Platform : 7.7.x, 7.5.x, 7.3.x; also confirmed with Apache Kafka 3.3.x
- confluent-kafka-javascript version: ^0.5.2

**Steps to Reproduce**

- Launch Kafka in docker or in AWS MSK
- Create a topic with the `gzip` compression
- Initiate a producer and pass the compression param as specified in the documentation: https://github.com/confluentinc/confluent-kafka-javascript/blob/master/MIGRATION.md#producer
- Try to write a 1 MB message with compression

Result: The following error: `Error running producer: LibrdKafkaError: Broker: Message size too large` is thrown, however, the same message is sent as expected  using `kafkajs`

The code with `confluent-kafka-javascript`:
```
const { Kafka } = require('@confluentinc/kafka-javascript').KafkaJS;

const topic = 'ContentUpdatedTopic';
const clientId = 'test-client-id';

const kafka = new Kafka({
	kafkaJS: {
		clientId: clientId,
		brokers: ['localhost:9092'],
		logLevel: 4,
	},
});

const producerRun = async () => {
	const producer = kafka.producer({
		kafkaJS: {
			compression: 'GZIP',
		},
	});

	await producer.connect();
	console.log('Producer connected');

	const oneMbString = 'a'.repeat(1048576);

	await producer.send({
		topic,
		messages: [
			{
				key: 'test-key',
				value: oneMbString,
			},
		],
	});


	await producer.disconnect();
	console.log('Producer disconnected');
};

producerRun().catch((err) => {
	console.error('Error running producer:', err);
});
```

The same code but with `kafkajs`:
```
const { Kafka, CompressionTypes } = require('kafkajs');

const topic = 'ContentUpdatedTopic';
const clientId = 'test-client-id';

const kafka = new Kafka({
	clientId,
	brokers: ['localhost:9092'],
});

const producer = kafka.producer();

const run = async () => {
	await producer.connect();

	const oneMbString = 'a'.repeat(1048576);

	await producer.send({
		topic,
		compression: CompressionTypes.GZIP,
		messages: [
			{ key: 'test-key', value: oneMbString },
		],
	});
	console.log('message sent');

	await producer.disconnect();
};

run().catch(console.error);
```

**Comment by milindl** [comment]
Thanks for filing this @maksym-opanasenko-ft .  

I think the error message is a little confusing, as it's not the broker rejecting the message, but instead, the library rejecting the message for being too large (uncompressed).

You can change one config property to fix this, it will be
```
	const producer = kafka.producer({
		kafkaJS: {
			compression: 'GZIP',
		},
		'message.max.bytes': 2048576, // or choose your number, this includes some overhead for there are things in the msg except just the value
	});
```
With this I checked, the uncompressed message size is 1048597 (including 1mb value + the overhead) and compressed size is 1074 bytes as it's sent to the broker successfully. 

[There is some more discussion here for reference.](https://github.com/confluentinc/librdkafka/issues/3125)

**Comment by milindl** [comment]
Closing this with my answer above, please reopen if there's another issue around this.
