### ISSUE TITLE
[Question] [KafkaJS] Support for AWS-MSK IAM authentication and/or custom authentication?

### ISSUE THREAD

**Issue by snypelife** [confluentinc/confluent-kafka-javascript#219]
KafkaJS appears to support [AWS-MSK](https://kafka.js.org/docs/configuration#aws-iam-example) as well as a [plugin based authentication mechanism](https://kafka.js.org/docs/configuration#custom-authentication-mechanisms).

Based on the available types, neither of these mechanisms are supported out of the box currently.

Are there any known patterns for connecting to MSK with the KafkaJS strategy?

If not, will this be considered for future enhancement?

Thanks!

**Comment by milindl** [comment]
We don't provide support for IAM-based auth to MSK, and we don't plan to do that.

As for pluggable authentication, there is no short-term plan in the future.

However, MSK does support OAUTHBEARER based authentication as described here: https://aws.amazon.com/blogs/big-data/amazon-msk-iam-authentication-now-supports-all-programming-languages/

AWS's JavaScript implementation for it: https://github.com/aws/aws-msk-iam-sasl-signer-js

I think the example provided in the blog post should work pretty well with this client. You can see the example of using oauthBearerProvider [here](https://github.com/confluentinc/confluent-kafka-javascript/blob/master/examples/kafkajs/oauthbearer_calback_authentication/oauthbearer_callback_authentication.js#L45). 

In addition to the token, you'll need to set the expiryMs (which seems to be available as `.expiryTime` on the return type of `generateAuthToken`) and also the principal, which it _seems_ like you can set to an arbitrary string in this case.

**Comment by snypelife** [comment]
Totally understood. Thank you so much for the quick response, it's super helpful and greatly appreciated! :pray:
