### ISSUE TITLE
Request: TypeScript example of KafkaJS

### ISSUE THREAD

**Issue by abrkn** [confluentinc/confluent-kafka-javascript#33]
I'm not understanding how to construct an instance of `KafkaJS.Kafka` since `KafkaJS` is exported as a `type` and not a namespace. Are there any examples of this?

**Comment by abrkn** [comment]
Thanks, let me know if you need help. Would love to migrate away from KafkaJS

**Comment by milindl** [comment]
I added the examples and fixed the types. I've not created a release yet with the fixes, but if you want to try it out before that you can install it from GitHub too (`npm install "git+https://git@github.com/confluentinc/confluent-kafka-javascript.git"`)

**Comment by milindl** [comment]
I've made a release v0.1.12-devel, it's available on npm. You can use that to try.

**Comment by milindl** [comment]
Closing this as the typing are working and an example is added in the release.
