### ISSUE TITLE
Mismatches between`types/kafkajs.d.ts` and documentation

### ISSUE THREAD

**Issue by apeloquin-agilysys** [confluentinc/confluent-kafka-javascript#38]
While working on a conversion from KafkaJS, I've encountered the following:

- Per MIGRATION.md: _`acks`, `compression` and `timeout` are not set on a per-send basis_, yet `ProducerRecord` interface still contains `acks`, `compression`, and `timeout` leading one to believe these _can_ be set per message.
- According to MIGRATION.md `retry` option from existing KafkaJS config is supported, yet it is missing from `KafkaConfig` interface.
- No mention is made of supporting batch message handling in MIGRATION.md and `ConsumerRunConfig` type only includes `eachMessage?: EachMessageHandler` and not `eachBatch?: EachBatchHandler`, yet `EachBatchHandler` and its supporting types are still present.
- `compression` in producer config (and in _kafkajs.d.ts_) says to use the `CompressionTypes` enum.  Doing so results in error message like: _Error: Invalid value "3" for configuration property "compression.codec"_.  To get this working, I had to use the native values from compression.codec: `'none' | 'gzip' | 'snappy' | 'lz4' | 'zstd'` and in code ` as unknown as CompressionTypes` to avoid compile-time errors.
- the consumer `on` event methods are present in _kafkajs.d.ts_, they are not mentioned in MIGRATION.md, but use of them throws a "not implemented" error.  Is the goal to provide implementation for these?

**Comment by milindl** [comment]
Thanks for filing this issue - I'll fix the discrepancies. About the `on` methods, we don't plan to implement them yet. For the rest, I'll be updating the types.

**Comment by mlois-efimob** [comment]
@milindl I think I find another typo on KafkaJS types, we are migrating from KafkaJs client library, but we still need to use:

```
compression: 'snappy' as KafkaJS.CompressionTypes
```

because in the js code (runtime):
```javascriot
const CompressionTypes = {
  None: 'none',
  GZIP: 'gzip',
  SNAPPY: 'snappy',
  LZ4: 'lz4',
  ZSTD: 'zstd',
};
```
TS Types
```javascriot
export enum CompressionTypes {
  None = 'none',
  GZIP = 'gzip',
  Snappy = 'snappy',
  LZ4 = 'lz4',
  ZSTD = 'zstd',
}
```

The Snappy vs SNAPPY case discrepancy is still present on latest release.

I can submit a PR if required.
