### ISSUE TITLE
Why is binding better than native implementation?

### ISSUE THREAD

**Issue by sashahohloma** [confluentinc/confluent-kafka-javascript#44]
In our project, we plan to use Kafka for cross-service data exchange, but we are put off by the available choice of clients. Many clients look abandoned, including previously popular ones (for example, `kafkajs` or `node-kafka`). The only solutions are `node-rdkafka` or `confluent-kafka-javascript` based on `librdkafka`. There is currently no popular client for Kafka in the NodeJS community with active support without third-party dependencies, unlike RabbitMQ or NATS. Using bindings creates additional complexity when using applications on different platforms, and also requires studying the `librdkafka` documentation, which can be difficult for NodeJS developers without knowledge of other programming languages.

Is there a chance that an official client based on NodeJS will be introduced in the future?

**Comment by nhaq-confluent** [comment]
Hey @sashahohloma that is a great question.

As you may know at Confluent, we officially support multiple libraries, including confluent-kafka-go, confluent-kafka-python, confluent-kafka-dotnet, librdkafka and when this library goes GA, it will become officially supported as well. 

We have noticed that our strategy of building up in librdkafka and then provide language bindings has shown lots of benefits, including our ability to release all libraries in tandem, be at the forefront of bringing new KIPs from Apache Kafka into the non-Java ecosystem and in many cases, noticeable performance gains. These benefits are why we currently don't foresee the release of any native libraries. Of course, your points about the drawbacks of the binding approach are valid, and we understand in some cases it can introduce additional complexities. 

Regarding the documentation point of yours, I would like to hear more about which parts you think can be streamlined or simplified, so we make sure that Node developers can find the available resources effective as they look to use this library. 

Thank you.

**Comment by nhaq-confluent** [comment]
@sashahohloma I completely agree that there are many benefits to native clients. 

As you mentioned, the two popular clients today for nodejs are kafkajs (native) and node-rdkafka (binded). With our client, we aim for users to have a way to migrate from both if they so choose. 

We aim that despite the typical challenges brought from a binded client, we can still deliver a strong developer experience, and welcome and suggestions, feedback and issues here on GitHub in pursuit of that goal.
