### ISSUE TITLE
Understanding the roadmap 

### ISSUE THREAD

**Issue by dclarke** [confluentinc/confluent-kafka-javascript#50]
I wanted to get a better understanding of what are the roadmap items that are left before we enter Beta or GA. 
It would be good to have a bit of visibility into the project, beyond the issues that are filed . 

Thanks

**Comment by nhaq-confluent** [comment]
Hey @dclarke thank you for the question. Hopefully I can shed some light on this. There are a few aspects to what needs to be done prior to when we feel comfortable making this product GA. 

1. Core Client and API progression: as you may know, one of our aims was to provide a promisified API syntax for the functionality in this client. For the EA, we only had basic produce/consume and some topic methods following this approach. For GA, we have a list of other APIs that we want to get in this format as well to help facilitate migration of users coming from KafkaJS
2. Stability and quality: we want to make sure we are content with the quality and stability of our code before we make it available for GA and for production workloads

The other aspect is how we approach general availability in regards to schema registry support, which we want to have a clear path forward before GA
