### ISSUE TITLE
[Enhancement] Roadmap or more info on path to production ready

### ISSUE THREAD

**Issue by gavinroderick** [confluentinc/confluent-kafka-javascript#56]
Hi there! 

Looking into this library for potential use at my company - it would be great if there was some kind of roadmap, rough timeline, or even MVP scope for this project, so we can evaluate if we'll be able to use it in the near term, or use another library initially and migrate here longer term. 

I understand giving estimates on projects like this is a bit of a nightmare, but even something like "maybe this year, next year H1, next year H2" would be a massive help! 

Thanks 🚀

**Comment by nhaq-confluent** [comment]
Hey @gavinroderick we are still on a path to provide a general availability that is complete with all features including Confluent Schema Registry as well as support by Confluent's GTS team by the end of the year.

**Comment by gavinroderick** [comment]
Amazing, thanks for the info! Will feed it back to the team!
