### ISSUE TITLE
ConfluentJavascript.KafkaJS.Consumer["assignment"] typings incorrect

### ISSUE THREAD

**Issue by justjake** [confluentinc/confluent-kafka-javascript#60]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: macOS 14.5 (23F79)
 - Node Version [e.g. 8.2.1]: v18.17.0
 - NPM Version [e.g. 5.4.2]: 9.6.7
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: Xcode 14
 - confluent-kafka-javascript version [e.g. 2.3.3]: `"@confluentinc/kafka-javascript": "0.1.16-devel"`

**Steps to Reproduce**

The typings for `ConfluentJavascript.KafkaJS.Consumer["assignment"]` is wrong for me.

The typing in the Javascript source code comment has the return type is `import("../../types/kafkajs").TopicPartition[]` aka `Array<{ topic: string, partition: number }>`, but the typing in the type declaration file used by Typescript and my IDE is `TopicPartitions[]` aka `Array<{ topic: string, partitions: number[] }>`. This caused a runtime error in my code

**confluent-kafka-javascript Configuration Settings**

n/a

**Additional context**

n/a

**Comment by milindl** [comment]
Closing with release 0.1.17-devel
