### ISSUE TITLE
Confluent client unexpectedly mutates function arguments

### ISSUE THREAD

**Issue by justjake** [confluentinc/confluent-kafka-javascript#61]
The KafkaJS consumer unexpected mutates the inputs to some of its methods. For example, `kafkaJSClient.pause(topics)` will mutate the input topics by adding the `.partitions` key if it's undefined. I generally expect that Javascript functions treat their inputs as immutable, so I don't need to defensively clone function arguments before passing them to a library. Mutation can lead to unexpected results.

In this case, I want to call `.pause(assignments)` during the rebalance callback for some assignments. This is mutating the assignment objects, leading to unexpected side effects in the assignment logic.

**Comment by milindl** [comment]
Yes, that's right, I'll change this and check other functions, too, we shouldn't be mutating arguments.
