### ISSUE TITLE
how to active acl managment on the confluentinc/cp-kafka:7.4.6

### ISSUE THREAD

**Issue by ariyaee1367** [confluentinc/confluent-kafka-javascript#76]
How to active acl management on the confluentinc/cp-kafka:7.4.6  ? 
my cluster deploy with docker-compose and here is my compose file : 

version: "3"
services:
  kafka-console:
    image: vectorized/console:v2.7.2
    container_name: kafka-console
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
            #  KAFKA_BROKERS: 172.30.0.3:9093
            # CONNECT_ZOOKEEPER_ENABLED: "true"
      #     KAFKA_ZOOKEEPER: "172.30.0.6:2181"
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers:
            - 172.30.0.3:9093
          sasl:
            enabled: true
            username: "kafka"
            password: "admin-123"
            mechanism: PLAIN
    ports:
      - 9001:8080
    networks:
      stack:
        ipv4_address: 172.30.0.2
##################################################################################################################
  zookeeper-n1:
    image: confluentinc/cp-zookeeper:7.4.6
    restart: always
    container_name: zookeeper-n1
    extra_hosts:
      - "zookeeper-n1:172.30.0.6"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SASL_ENABLED: 'false'
    expose:
      - 2181
    networks:
      stack:
        ipv4_address: 172.30.0.6
###################################################################################################################
  kafka-n1:
    image: confluentinc/cp-kafka:7.4.6
    depends_on:
      - zookeeper-n1
    container_name: kafka-n1
    restart: always
    ports:
      - 9092:9092
      - 9093:9093
        #  command: sleep 300
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_ZOOKEEPER_CONNECT: '172.30.0.6:2181'
      ZOOKEEPER_SASL_ENABLED: 'false'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.30.0.3:9092, SASL_PLAINTEXT://172.30.0.3:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/configs/kafka_server_jaas.conf"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
    volumes:
      - "./configs:/etc/kafka/configs"
      - "./kafka-1/:/etc/kafka/"
    networks:
      stack:
        ipv4_address: 172.30.0.3
####################################################################################################################
networks:
  stack:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
Also here is kafka_server_jaas.conf file : 
KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="kafka"
  password="admin-123"
  user_kafka="admin-123";
};
And also here is  kafka_client_jaas.conf file : 

KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="client"
    password="admin-123";
};
Also add bellow config on the file :  server.properties
authorizer.class.name=kafka.security.authorizer.AclAuthorizer
when my kafka container be up due to the env defined on the kafka docker-compose , bellow config automate addedd on the  kafka.properties file : 
security.inter.broker.protocol=SASL_PLAINTEXT
advertised.listeners=PLAINTEXT://172.30.0.3:9092, SASL_PLAINTEXT://172.30.0.3:9093
sasl.enabled.mechanisms=PLAIN
listener.security.protocol.map=PLAINTEXT:PLAINTEXT, SASL_PLAINTEXT:SASL_PLAINTEXT
authorizer.class.name=kafka.security.authorizer.AclAuthorizer
broker.id=1
listeners=PLAINTEXT://0.0.0.0:9092, SASL_PLAINTEXT://0.0.0.0:9093
zookeeper.connect=172.30.0.6:2181
sasl.mechanism.inter.broker.protocol=PLAIN
log.dirs=/var/lib/kafka/data

Now awhen ttach kafka container  and run bellow command : 
kafka-acls --bootstrap-server 172.30.0.3:9093 --command-config /etc/kafka/configs/kafka_client_jaas.conf --list
my kafka container generete bellow error : 
hannelId=172.30.0.3:9093-172.30.0.3:55242-173) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)
[2024-09-10 05:36:29,312] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1] Failed authentication with /172.30.0.3 (channelId=172.30.0.3:9093-172.30.0.3:55244-173) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)
[2024-09-10 05:36:29,715] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1] Failed authentication with /172.30.0.3 (channelId=172.30.0.3:9093-172.30.0.3:55254-173) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)
Every one can help me for resolve the issue ?

**Comment by milindl** [comment]
Hi @ariyaee1367 , I don't quite understand the issue. How are you using the Javascript client exactly?

**Comment by ariyaee1367** [comment]
> Hi @ariyaee1367 , I don't quite understand the issue. How are you using the Javascript client exactly?

i want active  acl on kafka bitnami container , just use acl for clinet connection with my kafka .  and also i want use Kraft mode with single node kafka . can tou send me docker-compose file ?

**Comment by milindl** [comment]
You can check in the confluent community slack https://developer.confluent.io/community/ask-the-community/ for better guidance regarding CP. 

This is specifically the repo for the javascript client only.
